#!/bin/sh

path=$2
if [ "$path" == "" ]; then
    path=`pwd`
	fi

	output='.ctags'

	case $1 in
	php)
		ctags \
            -f $output \
            -h '.php' \
            --append=yes \
            --recurse=yes \
            --totals=yes \
            --tag-relative=yes \
            --exclude='*.js' \
            --exclude='*.css' \
            --exclude='*.html' \
            --exclude='.git' \
            --exclude='.svn' \
            --fields=+afks \
            --PHP-kinds=+cidf-v \
            $path
    ;;
    *)
        echo "Usage: language [path]"
    ;;
esac
